name: Run main.py

on:
  workflow_dispatch:
    ref: main
    inputs:
      type:
        description: 'wedding | etc..'
        required: true
        default: 'wedding'

jobs:
  app:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.9
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'
          architecture: x64
      - name: Cache pip
        uses: actions/cache@v2
        id: cache
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-
      - name: Install dependencies
        if: steps.cache.outputs.cache-hit != 'true'
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Output env file
        run: echo "WEBHOOK_URL=${{ secrets.WEBHOOK_URL }}" > .env
      - name: Decrypt json
        run: sh decrypt_secret.sh
      - name: run main
        run: python main.py "${{ github.event.inputs.type }}"


