name: Run main.py

on:
  workflow_dispatch:
    ref: main
    inputs:
      type:
        description: 'first or next'
        required: true

jobs:
  app:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.9
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'
          architecture: x64
      - name: Install dependencies
        if: steps.cache.outputs.cache-hit != 'true'
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Output env file
        run: echo "WEBHOOK_URL=${{ secrets.WEBHOOK_URL }}" > .env
      - name: Decrypt json
        env:
          SECRET_PASSPHRASE: "${{ secrets.SECRET_PASSPHRASE }}"
        run: sh decrypt_secret.sh
      - name: run main
        env:
          TZ: 'Asia/Tokyo'
        run: python main.py
